name: Java CI with Maven - Test and package

# Déclenchement lors d'une pull request sur la branche main
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Configurer Java avec la version 21 et la distribution corretto
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      # Étape 3 : Construire le projet avec Maven et exécuter les tests
      - name: Build with Maven
        run: mvn -B package
